name: agconnect_cloudstorage_example
description: Demonstrates how to use the agconnect_cloudstorage plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  agconnect_cloudstorage:
    path: ../
  cupertino_icons: 1.0.3
  path_provider: 2.0.5
  image_picker: 0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
